
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class Hotel_booking_coxs_bazar extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_booking_coxs_bazar
     */
    public Hotel_booking_coxs_bazar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hotel_name = new javax.swing.JComboBox<>();
        check_in = new javax.swing.JComboBox<>();
        check_out = new javax.swing.JComboBox<>();
        room_type = new javax.swing.JComboBox<>();
        room_no = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        costtotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("HOTEL BOOKING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Hotel Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Check In Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Check Out Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Room Type");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rooms");

        hotel_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hotel_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Hotel Sea Crown", "Long Beach Hotel", "Grace Cox Smart Hotel" }));

        check_in.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_in.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "13/11/19", "14/11/19", "15/11/19" }));

        check_out.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_out.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "14/11/19", "15/11/19", "16/11/19", "17/11/19", "18/11/19", "19/11/19", "20/11/19" }));

        room_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        room_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Single", "Double" }));

        room_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        room_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1", "2", "3", "4", "5" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("View Hotel Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        costtotal.setEditable(false);
        costtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hotel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(check_in, 0, 210, Short.MAX_VALUE)
                        .addComponent(check_out, 0, 210, Short.MAX_VALUE)
                        .addComponent(room_type, 0, 210, Short.MAX_VALUE)
                        .addComponent(room_no, 0, 210, Short.MAX_VALUE)
                        .addComponent(costtotal)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotel_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 630, 320));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 70, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("CONFIRM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 100, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 70, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 220, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(hotel_name.getSelectedItem().equals("None"))
        {
            JOptionPane.showMessageDialog(null, "Select A Hotel");
        }
        else if(hotel_name.getSelectedItem().equals("Hotel Sea Crown"))
        {
            new Hotel_sea_crown().setVisible(true);
            this.dispose();
        }
        else if(hotel_name.getSelectedItem().equals("Long Beach Hotel"))
        {
            new Long_beach_hotel().setVisible(true);
            this.dispose();
        }
        else if(hotel_name.getSelectedItem().equals("Grace Cox Smart Hotel"))
        {
            new Grace_cox_smart_hotel().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        costtotal.setText(null);
        if(hotel_name.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select a Hotel");
        else if(check_in.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Check In Date");
        else if(check_out.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Check Out Date");
        else if(room_type.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Room Type");
        else if(room_no.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Number of Rooms");
        else{
        int cost=0;
        int chk_in=0,chk_out=0;
            if(check_in.getSelectedItem().equals("13/11/19")) chk_in=1;
            else if(check_in.getSelectedItem().equals("14/11/19")) chk_in=2;
            else if(check_in.getSelectedItem().equals("15/11/19")) chk_in=3;
            if(check_out.getSelectedItem().equals("14/11/19")) chk_out=2;
            else if(check_out.getSelectedItem().equals("15/11/19")) chk_out=3;
            else if(check_out.getSelectedItem().equals("16/11/19")) chk_out=4;
            else if(check_out.getSelectedItem().equals("17/11/19")) chk_out=5;
            else if(check_out.getSelectedItem().equals("18/11/19")) chk_out=6;
            else if(check_out.getSelectedItem().equals("19/11/19")) chk_out=7;
            else if(check_out.getSelectedItem().equals("20/11/19")) chk_out=8;
        if(chk_in>=chk_out) JOptionPane.showMessageDialog(null, "Please Select Valid Check Out Date");
        else
        {
            if (hotel_name.getSelectedItem().equals("Hotel Sea Crown")) 
            {
                if(room_type.getSelectedItem().equals("Single")) cost=1000;
                else cost=2000;
            }
            else if (hotel_name.getSelectedItem().equals("Long Beach Hotel")) 
            {
                if(room_type.getSelectedItem().equals("Single")) cost=1500;
                else cost=3000;
            }
            else
            {
                if(room_type.getSelectedItem().equals("Single")) cost=800;
                else cost=1500;
            }
            String rm_no=room_no.getSelectedItem().toString();
            int r_no=Integer.parseInt(rm_no);
            cost = cost*r_no;
            cost = cost * (chk_out - chk_in);
            String COST=String.format("%d", cost);
            costtotal.setText(COST);
            
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    JFrame frame;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Travel Management System",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(hotel_name.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select a Hotel");
        else if(check_in.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Check In Date");
        else if(check_out.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Check Out Date");
        else if(room_type.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Room Type");
        else if(room_no.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Number of Rooms");
        else
        {
            ArrayList<String> lines = new ArrayList<String>();
            String line;
            int chk_in=0,chk_out=0;
            if(check_in.getSelectedItem().equals("13/11/19")) chk_in=1;
            else if(check_in.getSelectedItem().equals("14/11/19")) chk_in=2;
            else if(check_in.getSelectedItem().equals("15/11/19")) chk_in=3;
            if(check_out.getSelectedItem().equals("14/11/19")) chk_out=2;
            else if(check_out.getSelectedItem().equals("15/11/19")) chk_out=3;
            else if(check_out.getSelectedItem().equals("16/11/19")) chk_out=4;
            else if(check_out.getSelectedItem().equals("17/11/19")) chk_out=5;
            else if(check_out.getSelectedItem().equals("18/11/19")) chk_out=6;
            else if(check_out.getSelectedItem().equals("19/11/19")) chk_out=7;
            else if(check_out.getSelectedItem().equals("20/11/19")) chk_out=8;
            if(chk_in>=chk_out) JOptionPane.showMessageDialog(null, "Please Select Valid Check Out Date");
            else
            {
                int nod=chk_out-chk_in;
                try {
                    File file;
                    if(hotel_name.getSelectedItem().equals("Hotel Sea Crown")) 
                        file= new File("C:\\Users\\PC\\Documents\\NetBeansProjects\\Travel_management_system\\db\\hotel sea crown.txt");
                    else if(hotel_name.getSelectedItem().equals("Long Beach Hotel")) 
                        file= new File("C:\\Users\\PC\\Documents\\NetBeansProjects\\Travel_management_system\\db\\long beach hotel.txt");
                    else
                        file= new File("C:\\Users\\PC\\Documents\\NetBeansProjects\\Travel_management_system\\db\\grace cox smart hotel.txt");
                    FileReader fr = new FileReader(file);
                    BufferedReader br = new BufferedReader(fr);
                    String date, rm_tp, rm_no, rm_no_temp = room_no.getSelectedItem().toString();
                    int rn1, rn2 = Integer.parseInt(rm_no_temp);
                    boolean flag = true;
                    while ((line = br.readLine()) != null) {
                        date = line;
                        rm_tp = br.readLine();
                        rm_no = br.readLine();
                        if (check_in.getSelectedItem().equals(date) && room_type.getSelectedItem().equals(rm_tp)) {
                            for (int i = 0; i < nod; ++i) {
                                if (i != 0) {
                                    date = br.readLine();
                                    rm_tp = br.readLine();
                                    rm_no = br.readLine();
                                }
                                rn1 = Integer.parseInt(rm_no);
                                if (rn2 > rn1) {
                                    flag = false;
                                    break;
                                } else {
                                    rn1 = rn1 - rn2;
                                    rm_no = String.format("%d", rn1);
                                    lines.add(date);
                                    lines.add(rm_tp);
                                    lines.add(rm_no);
                                }
                            }
                            if (!flag) {
                                JOptionPane.showMessageDialog(null, "Sorry!! Selected rooms are booked!!");
                                break;
                            } else {
                                JOptionPane.showMessageDialog(null, "Booking Confirmed!!");
                            }
                        } else {
                            lines.add(date);
                            lines.add(rm_tp);
                            lines.add(rm_no);
                        }
                    }
                    br.close();
                    fr.close();
                    if(flag)
                    {
                        FileWriter fw = new FileWriter(file, false);
                        PrintWriter pw = new PrintWriter(fw);
                        for (String str : lines) {
                            pw.println(str);
                        }
                        pw.close();
                        fw.close();
                    }
                    new Menu().setVisible(true);
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_booking_coxs_bazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_booking_coxs_bazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_booking_coxs_bazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_booking_coxs_bazar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_booking_coxs_bazar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> check_in;
    private javax.swing.JComboBox<String> check_out;
    private javax.swing.JTextField costtotal;
    private javax.swing.JComboBox<String> hotel_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> room_no;
    private javax.swing.JComboBox<String> room_type;
    // End of variables declaration//GEN-END:variables
}
