/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class Transportation_booking extends javax.swing.JFrame {

    /**
     * Creates new form Transportation_booking
     */
    public Transportation_booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        departure = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        destination = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox<>();
        nonac = new javax.swing.JRadioButton();
        bus = new javax.swing.JRadioButton();
        train = new javax.swing.JRadioButton();
        ac = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        costtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seat_no = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Transporation Booking");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 120));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Departure Point");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        departure.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Dhaka", "Rajshahi", "Syleht" }));
        jPanel1.add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Destination");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 30));

        destination.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Cox's Bazar", "Bandarban", "Chittagong" }));
        jPanel1.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "13/11/19", "14/11/19", "15/11/19", "16/11/19", "17/11/19", "18/11/19", "19/11/19" }));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        nonac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nonac.setText("Non AC");
        nonac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonacActionPerformed(evt);
            }
        });
        jPanel1.add(nonac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, -1));

        bus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bus.setText("Bus");
        bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busActionPerformed(evt);
            }
        });
        jPanel1.add(bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, -1));

        train.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        train.setText("Train");
        train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainActionPerformed(evt);
            }
        });
        jPanel1.add(train, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, -1));

        ac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ac.setText("AC");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        jPanel1.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("TOTAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));

        costtotal.setEditable(false);
        jPanel1.add(costtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Seat No");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));

        seat_no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seat_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1", "2", "4" }));
        jPanel1.add(seat_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 360, 310));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("CONFIRM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 100, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 80, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, 10));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 80, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 590, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Travel Management System",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        costtotal.setText(null);
        if(departure.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Departure");
        else if(destination.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Destination");
        else if(seat_no.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Seat No");
        else if(!bus.isSelected() && !train.isSelected()) JOptionPane.showMessageDialog(null, "Select Transportation Mode");
        else if(!ac.isSelected() && !nonac.isSelected()) JOptionPane.showMessageDialog(null, "Select AC or Non AC");
        else if(train.isSelected() && departure.getSelectedItem().equals("Rajshahi")) JOptionPane.showMessageDialog(null, "No Such Train Found");
        else if(train.isSelected() && destination.getSelectedItem().equals("Cox's Bazar")) JOptionPane.showMessageDialog(null, "No Such Train Found");
        else if(train.isSelected() && destination.getSelectedItem().equals("Bandarban")) JOptionPane.showMessageDialog(null, "No Such Train Found");
        else{
        int cost=0;
        if(bus.isSelected())
        {
            if (departure.getSelectedItem().equals("Dhaka") && destination.getSelectedItem().equals("Cox's Bazar")) {
                if (ac.isSelected()) {
                    cost = 1500;
                } else {
                    cost = 1000;
                }
            } else if (departure.getSelectedItem().equals("Dhaka") && destination.getSelectedItem().equals("Bandarban")) {
                if (ac.isSelected()) {
                    cost = 1200;
                } else {
                    cost = 800;
                }
            } else if (departure.getSelectedItem().equals("Dhaka") && destination.getSelectedItem().equals("Chittagong")) {
                if (ac.isSelected()) {
                    cost = 1000;
                } else {
                    cost = 750;
                }
            } else if (departure.getSelectedItem().equals("Rajshahi") && destination.getSelectedItem().equals("Cox's Bazar")) {
                if (ac.isSelected()) {
                    cost = 2000;
                } else {
                    cost = 1500;
                }
            } else if (departure.getSelectedItem().equals("Rajshahi") && destination.getSelectedItem().equals("Bandarban")) {
                if (ac.isSelected()) {
                    cost = 1700;
                } else {
                    cost = 1300;
                }
            } else if (departure.getSelectedItem().equals("Rajshahi") && destination.getSelectedItem().equals("Chittagong")) {
                if (ac.isSelected()) {
                    cost = 1500;
                } else {
                    cost = 1250;
                }
            } else if (departure.getSelectedItem().equals("Syleht") && destination.getSelectedItem().equals("Cox's Bazar")) {
                if (ac.isSelected()) {
                    cost = 1800;
                } else {
                    cost = 1300;
                }
            } else if (departure.getSelectedItem().equals("Syleht") && destination.getSelectedItem().equals("Bandarban")) {
                if (ac.isSelected()) {
                    cost = 1600;
                } else {
                    cost = 1200;
                }
            } else if (departure.getSelectedItem().equals("Syleht") && destination.getSelectedItem().equals("Chittagong")) {
                if (ac.isSelected()) {
                    cost = 1500;
                } else {
                    cost = 1300;
                }
            }
        }
        else
        {
            if (departure.getSelectedItem().equals("Dhaka")) {
                if (ac.isSelected()) {
                    cost = 1000;
                } else {
                    cost = 800;
                }
            } else if (departure.getSelectedItem().equals("Syleht")) {
                if (ac.isSelected()) {
                    cost = 1500;
                } else {
                    cost = 1000;
                }
            } 
        }
        if(seat_no.getSelectedItem().equals("2"))
        {
            cost=cost*2;
        }
        else if(seat_no.getSelectedItem().equals("4"))
        {
            cost=cost*4;
        }
        String COST=String.format("%d", cost);
        costtotal.setText(COST);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(departure.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Departure");
        else if(destination.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Destination");
        else if(seat_no.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Seat No");
        else if(date.getSelectedItem().equals("None")) JOptionPane.showMessageDialog(null, "Select Date");
        else if(!bus.isSelected() && !train.isSelected()) JOptionPane.showMessageDialog(null, "Select Transportation Mode");
        else if(!ac.isSelected() && !nonac.isSelected()) JOptionPane.showMessageDialog(null, "Select AC or Non AC");
        else if(train.isSelected() && departure.getSelectedItem().equals("Rajshahi")) JOptionPane.showMessageDialog(null, "No Such Train Found");
        else if(train.isSelected() && destination.getSelectedItem().equals("Cox's Bazar")) JOptionPane.showMessageDialog(null, "No Such Train Found");
        else if(train.isSelected() && destination.getSelectedItem().equals("Bandarban")) JOptionPane.showMessageDialog(null, "No Such Train Found");
        else 
        {
            ArrayList<String> lines = new ArrayList<String>();
            String line;
            try
            {
                File file = new File("C:\\Users\\PC\\Documents\\NetBeansProjects\\Travel_management_system\\db\\ticket.txt");
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String des,dep,mode,dt,ns;
                while((line = br.readLine())!=null)
                {
                    dep=line;
                    des=br.readLine();mode=br.readLine();dt=br.readLine();ns=br.readLine();
                    if(departure.getSelectedItem().equals(dep) && destination.getSelectedItem().equals(des)
                            && date.getSelectedItem().equals(dt) && ((bus.isSelected() && mode.equals("bus")) || (train.isSelected() && mode.equals("train"))))
                    {
                        int nos = Integer.parseInt(ns);
                        String nas=seat_no.getSelectedItem().toString();
                        int nas1=Integer.parseInt(nas);
                        if(nas1>nos) JOptionPane.showMessageDialog(null, "Sorry!! All seats are booked!!");
                        else {JOptionPane.showMessageDialog(null, "Booking Confirmed!!");nos-=nas1;}
                        ns=String.format("%d", nos);
                    }
                    lines.add(dep);
                    lines.add(des);
                    lines.add(mode);
                    lines.add(dt);
                    lines.add(ns);
                }
                br.close();
                fr.close();
                FileWriter fw = new FileWriter(file,false);
                PrintWriter pw = new PrintWriter(fw);
                for(String str : lines)
                {
                    pw.println(str);
                }
                pw.close();
                fw.close();
                new Menu().setVisible(true);
                this.dispose();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busActionPerformed
        // TODO add your handling code here:
        if(bus.isSelected())
        {
            train.setSelected(false);
        }
    }//GEN-LAST:event_busActionPerformed

    private void trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainActionPerformed
        // TODO add your handling code here:
        if(train.isSelected())
        {
            bus.setSelected(false);
        }
    }//GEN-LAST:event_trainActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
        if(ac.isSelected())
        {
            nonac.setSelected(false);
        }
    }//GEN-LAST:event_acActionPerformed

    private void nonacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonacActionPerformed
        // TODO add your handling code here:
        if(nonac.isSelected())
        {
            ac.setSelected(false);
        }
    }//GEN-LAST:event_nonacActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transportation_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transportation_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transportation_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transportation_booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transportation_booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ac;
    private javax.swing.JRadioButton bus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField costtotal;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JComboBox<String> departure;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton nonac;
    private javax.swing.JComboBox<String> seat_no;
    private javax.swing.JRadioButton train;
    // End of variables declaration//GEN-END:variables
}
